package model;
// Generated 05.Eki.2019 21:16:32 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Blog generated by hbm2java
 */
@Entity
@Table(name = "blog")
public class Blog implements java.io.Serializable {

	private Integer blogid;
	private String blogtitle;
	private String blogtext;
	private String blogimage;
	private String blogauthorimage;
	private String blogauthor;
	private String blogtextparagraph;

	public Blog() {
	}

	public Blog(String blogtitle, String blogtext, String blogimage, String blogauthorimage, String blogauthor) {
		this.blogtitle = blogtitle;
		this.blogtext = blogtext;
		this.blogimage = blogimage;
		this.blogauthorimage = blogauthorimage;
		this.blogauthor = blogauthor;
	}

	public Blog(String blogtitle, String blogtext, String blogimage, String blogauthorimage, String blogauthor,
			String blogtextparagraph) {
		this.blogtitle = blogtitle;
		this.blogtext = blogtext;
		this.blogimage = blogimage;
		this.blogauthorimage = blogauthorimage;
		this.blogauthor = blogauthor;
		this.blogtextparagraph = blogtextparagraph;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "blogid", unique = true, nullable = false)
	public Integer getBlogid() {
		return this.blogid;
	}

	public void setBlogid(Integer blogid) {
		this.blogid = blogid;
	}

	@Column(name = "blogtitle", nullable = false)
	public String getBlogtitle() {
		return this.blogtitle;
	}

	public void setBlogtitle(String blogtitle) {
		this.blogtitle = blogtitle;
	}

	@Column(name = "blogtext", nullable = false)
	public String getBlogtext() {
		return this.blogtext;
	}

	public void setBlogtext(String blogtext) {
		this.blogtext = blogtext;
	}

	@Column(name = "blogimage", nullable = false)
	public String getBlogimage() {
		return this.blogimage;
	}

	public void setBlogimage(String blogimage) {
		this.blogimage = blogimage;
	}

	@Column(name = "blogauthorimage", nullable = false)
	public String getBlogauthorimage() {
		return this.blogauthorimage;
	}

	public void setBlogauthorimage(String blogauthorimage) {
		this.blogauthorimage = blogauthorimage;
	}

	@Column(name = "blogauthor", nullable = false)
	public String getBlogauthor() {
		return this.blogauthor;
	}

	public void setBlogauthor(String blogauthor) {
		this.blogauthor = blogauthor;
	}

	@Column(name = "blogtextparagraph")
	public String getBlogtextparagraph() {
		return this.blogtextparagraph;
	}

	public void setBlogtextparagraph(String blogtextparagraph) {
		this.blogtextparagraph = blogtextparagraph;
	}

}
