package model;
// Generated 05.Eki.2019 21:16:32 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Neworder generated by hbm2java
 */
@Entity
@Table(name = "neworder")
public class Neworder implements java.io.Serializable {

	private Integer orderid;
	private String ordername;
	private String productname;
	private String orderstatus;
	private double orderprice;
	private String ordernote;
	private String orderphone;
	private String orderaddress;

	public Neworder() {
	}

	public Neworder(String ordername, String productname, String orderstatus, double orderprice, String ordernote,
			String orderphone, String orderaddress) {
		this.ordername = ordername;
		this.productname = productname;
		this.orderstatus = orderstatus;
		this.orderprice = orderprice;
		this.ordernote = ordernote;
		this.orderphone = orderphone;
		this.orderaddress = orderaddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "orderid", unique = true, nullable = false)
	public Integer getOrderid() {
		return this.orderid;
	}

	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	@Column(name = "ordername", nullable = false)
	public String getOrdername() {
		return this.ordername;
	}

	public void setOrdername(String ordername) {
		this.ordername = ordername;
	}

	@Column(name = "productname", nullable = false)
	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	@Column(name = "orderstatus", nullable = false)
	public String getOrderstatus() {
		return this.orderstatus;
	}

	public void setOrderstatus(String orderstatus) {
		this.orderstatus = orderstatus;
	}

	@Column(name = "orderprice", nullable = false, precision = 22, scale = 0)
	public double getOrderprice() {
		return this.orderprice;
	}

	public void setOrderprice(double orderprice) {
		this.orderprice = orderprice;
	}

	@Column(name = "ordernote", nullable = false)
	public String getOrdernote() {
		return this.ordernote;
	}

	public void setOrdernote(String ordernote) {
		this.ordernote = ordernote;
	}

	@Column(name = "orderphone", nullable = false)
	public String getOrderphone() {
		return this.orderphone;
	}

	public void setOrderphone(String orderphone) {
		this.orderphone = orderphone;
	}

	@Column(name = "orderaddress", nullable = false)
	public String getOrderaddress() {
		return this.orderaddress;
	}

	public void setOrderaddress(String orderaddress) {
		this.orderaddress = orderaddress;
	}

}
