package model;
// Generated 05.Eki.2019 21:16:32 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart")
public class Cart implements java.io.Serializable {

	private Integer cartid;
	private String productname;
	private double productprice;
	private String orderstatus;

	public Cart() {
	}

	public Cart(String productname, double productprice, String orderstatus) {
		this.productname = productname;
		this.productprice = productprice;
		this.orderstatus = orderstatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cartid", unique = true, nullable = false)
	public Integer getCartid() {
		return this.cartid;
	}

	public void setCartid(Integer cartid) {
		this.cartid = cartid;
	}

	@Column(name = "productname", nullable = false)
	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	@Column(name = "productprice", nullable = false, precision = 22, scale = 0)
	public double getProductprice() {
		return this.productprice;
	}

	public void setProductprice(double productprice) {
		this.productprice = productprice;
	}

	@Column(name = "orderstatus", nullable = false)
	public String getOrderstatus() {
		return this.orderstatus;
	}

	public void setOrderstatus(String orderstatus) {
		this.orderstatus = orderstatus;
	}

}
