package model;
// Generated 05.Eki.2019 21:16:32 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category")
public class Category implements java.io.Serializable {

	private Integer categoryid;
	private String categoryname;

	public Category() {
	}

	public Category(String categoryname) {
		this.categoryname = categoryname;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "categoryid", unique = true, nullable = false)
	public Integer getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	@Column(name = "categoryname", nullable = false)
	public String getCategoryname() {
		return this.categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

}
