package model;
// Generated 05.Eki.2019 21:16:32 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product implements java.io.Serializable {

	private Integer productid;
	private int categoryid;
	private String productname;
	private double productprice;
	private String producttext;
	private String productimage;

	public Product() {
	}

	public Product(int categoryid, String productname, double productprice, String producttext, String productimage) {
		this.categoryid = categoryid;
		this.productname = productname;
		this.productprice = productprice;
		this.producttext = producttext;
		this.productimage = productimage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "productid", unique = true, nullable = false)
	public Integer getProductid() {
		return this.productid;
	}

	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	@Column(name = "categoryid", nullable = false)
	public int getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(int categoryid) {
		this.categoryid = categoryid;
	}

	@Column(name = "productname", nullable = false)
	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	@Column(name = "productprice", nullable = false, precision = 22, scale = 0)
	public double getProductprice() {
		return this.productprice;
	}

	public void setProductprice(double productprice) {
		this.productprice = productprice;
	}

	@Column(name = "producttext", nullable = false)
	public String getProducttext() {
		return this.producttext;
	}

	public void setProducttext(String producttext) {
		this.producttext = producttext;
	}

	@Column(name = "productimage", nullable = false)
	public String getProductimage() {
		return this.productimage;
	}

	public void setProductimage(String productimage) {
		this.productimage = productimage;
	}

}
